import { CalendarDots, ArrowCounterClockwise } from "@phosphor-icons/react";
import type { ReviewCycle } from "../domain/reviewCycles";
import { formatSignalDate } from "../domain/metricSeries";
import "./review-cycle-strip.css";

export function ReviewCycleStrip({ cycles, selection, onSelect }: { cycles: ReviewCycle[]; selection: string | null; onSelect: (value: string) => void }) {
  const selected = selection === "current" ? cycles[0] : cycles.find((cycle) => cycle.id === selection);
  const cycle = selected ?? cycles[0]; if (!cycle) return null;
  return <section className="review-cycle-strip" data-testid="review-cycle-strip"><header><CalendarDots size={22} weight="thin" /><div><span>Ciclo bimestral</span><strong>{cycle.label}</strong></div><small>{cycle.current ? `Dia ${cycle.elapsedDays} de ${cycle.totalDays}` : "Período encerrado"}</small></header><progress value={cycle.elapsedDays} max={cycle.totalDays} aria-label="Dias decorridos do bimestre" /><div className="rc-dates"><span>{formatSignalDate(cycle.periodStart)}</span><span>{formatSignalDate(cycle.periodEnd)}</span></div><p>{cycle.current ? "Um novo ciclo começa a cada dois meses. O histórico continua nos painéis de 180 e 365 dias." : "Reveja este bimestre sem alterar os registros. O ciclo atual continua separado."}</p><div className="rc-actions"><button type="button" onClick={() => onSelect("current")} aria-pressed={selection === "current"}><ArrowCounterClockwise size={15} />Ver ciclo atual</button><select aria-label="Escolher bimestre" value={selection ?? ""} onChange={(event) => { if (event.target.value) onSelect(event.target.value); }}><option value="" disabled>Outros ciclos</option><option value="current">{cycles[0].label} · atual</option>{cycles.slice(1).map((item) => <option key={item.id} value={item.id}>{item.label}{item.clipped ? " · parcial" : ""}</option>)}</select></div>{selected ? <small className="rc-selection">Gráficos e relatório: {formatSignalDate(selected.window.start)} a {formatSignalDate(selected.window.end)}.{selected.clipped ? " Recorte limitado ao histórico disponível de 365 dias." : ""} Para voltar à janela móvel, escolha 7, 30, 60, 180 ou 365 dias acima.</small> : null}</section>;
}
